# ***************************************************************************************
# This is the User Defined Settings file which controls the complete execution
# Please see the Wiki for formatting details as setting descriptions.
#          https://github.com/daniel-fudge/DRL-Portfolio-Optimization/wiki
# ***************************************************************************************
tickers: [BCE.TO, RCI-B.TO, SJR-B.TO, T.TO, CJR-B.TO, MG.TO, TOY.TO, QSR.TO, GC.TO, GOOS.TO, CTC.TO, GIL.TO, DOL.TO, ATD-B.TO, L.TO, MRU.TO, SAP.TO, MFI.TO, ENB.TO, CNQ.TO, SU.TO, CVE.TO, ECA.TO, CPG.TO, TRP.TO, POU.TO, MEG.TO, PPL.TO, ALA.TO, WCP.TO, HSE.TO, BTE.TO, VET.TO, ARX.TO, MFC.TO, TD.TO, CM.TO, RY.TO, BNS.TO, BMO.TO, NA.TO, SLF.TO, POW.TO, LB.TO, GWO.TO, CWB.TO, EFN.TO, CIX.TO, TRI.TO, X.TO, ACB.TO, WEED.TO, APHA.TO, HEXO.TO, CRON.TO, BHC.TO, TGOD.TO, GUD.TO, XIU.TO, ZSP.TO, XEG.TO, XGD.TO, ZCN.TO, ZDM.TO, ZEB.TO, HMMJ.TO, NFI.TO, BBD-B.TO, AC.TO, CNR.TO, SNC.TO, CP.TO, FTT.TO, CAS.TO, TECK-B.TO, ABX.TO, YRI.TO, AEM.TO, HBM.TO, OGC.TO, LUN.TO, KL.TO, NTR.TO, LGO.TO, OR.TO, CUF-UN.TO, CAR-UN.TO, BB.TO, SHOP.TO, GIB-A.TO, OTEX.TO, MAXR.TO, LSPD.TO, CLS.TO, KXS.TO, CAD=X, FTS.TO, EMA.TO, CPX.TO, H.TO]

data_start:    2007-12-31
data_end:      2019-12-31
training_end:  2017-12-31
embedding_days:  63
prediction_days: [1, 5, 21]
